DELETE FROM Canton;

INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (1, 1, 'San José');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (2, 1, 'Escazú');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (3, 1, 'Desamparados');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (4, 1, 'Puriscal');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (5, 1, 'Tarrazú');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (6, 1, 'Aserrí');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (7, 1, 'Mora');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (8, 1, 'Goicoechea');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (9, 1, 'Santa Ana');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (10, 1, 'Alajuelita');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (11, 1, 'Vásquez de Coronado');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (12, 1, 'Acosta');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (13, 1, 'Tibás');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (14, 1, 'Moravia');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (15, 1, 'Montes de Oca');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (16, 1, 'Turrubares');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (17, 1, 'Dota');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (18, 1, 'Curridabat');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (19, 1, 'Pérez Zeledón');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (20, 1, 'León Cortéz Castro');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (21, 2, 'Alajuela');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (22, 2, 'San Ramón');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (23, 2, 'Grecia');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (24, 2, 'San Mateo');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (25, 2, 'Atenas');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (26, 2, 'Naranjo');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (27, 2, 'Palmares');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (28, 2, 'Poás');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (29, 2, 'Orotina');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (30, 2, 'San Carlos');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (31, 2, 'Zarcero');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (32, 2, 'Valverde Vega');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (33, 2, 'Upala');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (34, 2, 'Los Chiles');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (35, 2, 'Guatuso');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (36, 3, 'Cartago');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (37, 3, 'Paraíso');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (38, 3, 'La Unión');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (39, 3, 'Jiménez');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (40, 3, 'Turrialba');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (41, 3, 'Alvarado');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (42, 3, 'Oreamuno');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (43, 3, 'El Guarco');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (44, 4, 'Heredia');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (45, 4, 'Barva');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (46, 4, 'Santo Domingo');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (47, 4, 'Santa Bárbara');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (48, 4, 'San Rafaél');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (49, 4, 'San Isidro');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (50, 4, 'Belén');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (51, 4, 'Flores');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (52, 4, 'San Pablo');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (53, 4, 'Sarapiquí');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (54, 5, 'Liberia');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (55, 5, 'Nicoya');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (56, 5, 'Santa Cruz');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (57, 5, 'Bagaces');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (58, 5, 'Carrillo');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (59, 5, 'Cañas');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (60, 5, 'Abangáres');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (61, 5, 'Tilarán');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (62, 5, 'Nandayure');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (63, 5, 'La Cruz');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (64, 5, 'Hojancha');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (65, 6, 'Puntarenas');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (66, 6, 'Esparza');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (67, 6, 'Buenos Aires');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (68, 6, 'Montes de Oro');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (69, 6, 'Osa');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (70, 6, 'Aguirre');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (71, 6, 'Golfito');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (72, 6, 'Coto Brus');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (73, 6, 'Parrita');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (74, 6, 'Corredores');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (75, 6, 'Garabito');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (76, 7, 'Limón');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (77, 7, 'Pococí');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (78, 7, 'Siquirres');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (79, 7, 'Talamanca');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (80, 7, 'Matina');
INSERT INTO Canton (cantonID, provinciaID, nombre) VALUES (81, 7, 'Guácimo');


