DELETE FROM Distrito;
DBCC CHECKIDENT (Distrito, RESEED, 0);

SET IDENTITY_INSERT Distrito ON;

INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (1, 01, 'CARMEN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (2, 01, 'MERCED');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (3, 01, 'HOSPITAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (4, 01, 'CATEDRAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (5, 01, 'ZAPOTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (6, 01, 'SAN FRANCISCO DE DOS RÍOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (7, 01, 'URUCA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (8, 01, 'MATA REDONDA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (9, 01, 'PAVAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (10, 01, 'HATILLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (11, 01, 'SAN SEBASTIÁN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (12, 02, 'ESCAZÚ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (13, 02, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (14, 02, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (15, 03, 'DESAMPARADOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (16, 03, 'SAN MIGUEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (17, 03, 'SAN JUAN DE DIOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (18, 03, 'SAN RAFAEL ARRIBA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (19, 03, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (20, 03, 'FRAILES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (21, 03, 'PATARRÁ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (22, 03, 'SAN CRISTÓBAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (23, 03, 'ROSARIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (24, 03, 'DAMAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (25, 03, 'SAN RAFAEL ABAJO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (26, 03, 'GRAVILIAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (27, 03, 'LOS GUIDO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (28, 04, 'SANTIAGO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (29, 04, 'MERCEDES SUR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (30, 04, 'BARBACOAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (31, 04, 'GRIFO ALTO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (32, 04, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (33, 04, 'CANDELARITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (34, 04, 'DESAMPARADITOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (35, 04, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (36, 04, 'CHIRES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (37, 05, 'SAN MARCOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (38, 05, 'SAN LORENZO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (39, 05, 'SAN CARLOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (40, 06, 'ASERRI');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (41, 06, 'TARBACA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (42, 06, 'VUELTA DE JORCO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (43, 06, 'SAN GABRIEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (44, 06, 'LEGUA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (45, 06, 'MONTERREY');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (46, 06, 'SALITRILLOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (47, 07, 'COLÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (48, 07, 'GUAYABO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (49, 07, 'TABARCIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (50, 07, 'PIEDRAS NEGRAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (51, 07, 'PICAGRES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (52, 07, 'JARIS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (53, 07, 'QUITIRRISI');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (54, 08, 'GUADALUPE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (55, 08, 'SAN FRANCISCO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (56, 08, 'CALLE BLANCOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (57, 08, 'MATA DE PLÁTANO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (58, 08, 'IPÍS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (59, 08, 'RANCHO REDONDO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (60, 08, 'PURRAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (61, 09, 'SANTA ANA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (62, 09, 'SALITRAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (63, 09, 'POZOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (64, 09, 'URUCA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (65, 09, 'PIEDADES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (66, 09, 'BRASIL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (67, 10, 'ALAJUELITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (68, 10, 'SAN JOSECITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (69, 10, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (70, 10, 'CONCEPCIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (71, 10, 'SAN FELIPE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (72, 11, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (73, 11, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (74, 11, 'DULCE NOMBRE DE JESÚS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (75, 11, 'PATALILLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (76, 11, 'CASCAJAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (77, 12, 'SAN IGNACIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (78, 12, 'GUAITIL Villa');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (79, 12, 'PALMICHAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (80, 12, 'CANGREJAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (81, 12, 'SABANILLAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (82, 13, 'SAN JUAN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (83, 13, 'CINCO ESQUINAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (84, 13, 'ANSELMO LLORENTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (85, 13, 'LEON XIII');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (86, 13, 'COLIMA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (87, 14, 'SAN VICENTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (88, 14, 'SAN JERÓNIMO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (89, 14, 'LA TRINIDAD');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (90, 15, 'SAN PEDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (91, 15, 'SABANILLA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (92, 15, 'MERCEDES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (93, 15, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (94, 16, 'SAN PABLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (95, 16, 'SAN PEDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (96, 16, 'SAN JUAN DE MATA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (97, 16, 'SAN LUIS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (98, 16, 'CARARA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (99, 17, 'SANTA MARÍA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (100, 17, 'JARDÍN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (101, 17, 'COPEY');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (102, 18, 'CURRIDABAT');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (103, 18, 'GRANADILLA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (104, 18, 'SÁNCHEZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (105, 18, 'TIRRASES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (106, 19, 'SAN ISIDRO DE EL GENERAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (107, 19, 'EL GENERAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (108, 19, 'DANIEL FLORES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (109, 19, 'RIVAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (110, 19, 'SAN PEDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (111, 19, 'PLATANARES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (112, 19, 'PEJIBAYE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (113, 19, 'CAJÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (114, 19, 'BARÚ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (115, 19, 'RÍO NUEVO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (116, 19, 'PÁRAMO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (117, 20, 'SAN PABLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (118, 20, 'SAN ANDRÉS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (119, 20, 'LLANO BONITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (120, 20, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (121, 20, 'SANTA CRUZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (122, 20, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (123, 21, 'ALAJUELA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (124, 21, 'SAN JOSÉ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (125, 21, 'CARRIZAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (126, 21, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (127, 21, 'GUÁCIMA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (128, 21, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (129, 21, 'SABANILLA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (130, 21, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (131, 21, 'RÍO SEGUNDO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (132, 21, 'DESAMPARADOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (133, 21, 'TURRÚCARES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (134, 21, 'TAMBOR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (135, 21, 'GARITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (136, 21, 'SARAPIQUÍ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (137, 22, 'SAN RAMÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (138, 22, 'SANTIAGO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (139, 22, 'SAN JUAN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (140, 22, 'PIEDADES NORTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (141, 22, 'PIEDADES SUR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (142, 22, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (143, 22, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (144, 22, 'ÁNGELES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (145, 22, 'ALFARO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (146, 22, 'VOLIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (147, 22, 'CONCEPCIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (148, 22, 'ZAPOTAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (149, 22, 'PEÑAS BLANCAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (150, 23, 'GRECIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (151, 23, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (152, 23, 'SAN JOSÉ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (153, 23, 'SAN ROQUE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (154, 23, 'TACARES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (155, 23, 'RÍO CUARTO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (156, 23, 'PUENTE DE PIEDRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (157, 23, 'BOLÍVAR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (158, 24, 'SAN MATEO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (159, 24, 'DESMONTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (160, 24, 'JESÚS MARÍA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (161, 24, 'LABRADOR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (162, 25, 'ATENAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (163, 25, 'JESÚS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (164, 25, 'MERCEDES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (165, 25, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (166, 25, 'CONCEPCIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (167, 25, 'SAN JOSE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (168, 25, 'SANTA EULALIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (169, 25, 'ESCOBAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (170, 26, 'NARANJO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (171, 26, 'SAN MIGUEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (172, 26, 'SAN JOSÉ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (173, 26, 'CIRRÍ SUR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (174, 26, 'SAN JERÓNIMO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (175, 26, 'SAN JUAN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (176, 26, 'EL ROSARIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (177, 26, 'PALMITOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (178, 27, 'PALMARES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (179, 27, 'ZARAGOZA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (180, 27, 'BUENOS AIRES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (181, 27, 'SANTIAGO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (182, 27, 'CANDELARIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (183, 27, 'ESQUÍPULAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (184, 27, 'LA GRANJA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (185, 28, 'SAN PEDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (186, 28, 'SAN JUAN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (187, 28, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (188, 28, 'CARRILLOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (189, 28, 'SABANA REDONDA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (190, 29, 'OROTINA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (191, 29, 'EL MASTATE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (192, 29, 'HACIENDA VIEJA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (193, 29, 'COYOLAR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (194, 29, 'LA CEIBA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (195, 30, 'QUESADA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (196, 30, 'FLORENCIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (197, 30, 'BUENAVISTA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (198, 30, 'AGUAS ZARCAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (199, 30, 'VENECIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (200, 30, 'PITAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (201, 30, 'LA FORTUNA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (202, 30, 'LA TIGRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (203, 30, 'LA PALMERA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (204, 30, 'VENADO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (205, 30, 'CUTRIS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (206, 30, 'MONTERREY');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (207, 30, 'POCOSOL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (208, 31, 'ZARCERO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (209, 31, 'LAGUNA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (210, 31, 'GUADALUPE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (211, 31, 'PALMIRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (212, 31, 'ZAPOTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (213, 31, 'BRISAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (214, 32, 'SARCHÍ NORTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (215, 32, 'SARCHÍ SUR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (216, 32, 'TORO AMARILLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (217, 32, 'SAN PEDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (218, 32, 'RODRÍGUEZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (219, 33, 'UPALA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (220, 33, 'AGUAS CLARAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (221, 33, 'SAN JOSÉ o PIZOTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (222, 33, 'BIJAGUA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (223, 33, 'DELICIAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (224, 33, 'DOS RÍOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (225, 33, 'YOLILLAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (226, 33, 'CANALETE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (227, 34, 'LOS CHILES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (228, 34, 'CAÑO NEGRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (229, 34, 'EL AMPARO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (230, 34, 'SAN JORGE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (231, 35, 'BUENAVISTA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (232, 35, 'COTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (233, 35, 'KATIRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (234, 36, 'ORIENTAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (235, 36, 'OCCIDENTAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (236, 36, 'CARMEN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (237, 36, 'SAN NICOLÁS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (238, 36, 'AGUACALIENTE o SAN FRANCISCO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (239, 36, 'GUADALUPE o ARENILLA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (240, 36, 'CORRALILLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (241, 36, 'TIERRA BLANCA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (242, 36, 'DULCE NOMBRE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (243, 36, 'LLANO GRANDE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (244, 36, 'QUEBRADILLA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (245, 37, 'PARAÍSO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (246, 37, 'SANTIAGO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (247, 37, 'OROSI');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (248, 37, 'CACHÍ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (249, 37, 'LLANOS DE SANTA LUCÍA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (250, 38, 'TRES RÍOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (251, 38, 'SAN DIEGO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (252, 38, 'SAN JUAN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (253, 38, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (254, 38, 'CONCEPCIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (255, 38, 'DULCE NOMBRE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (256, 38, 'SAN RAMÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (257, 38, 'RÍO AZUL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (258, 39, 'JUAN VIÑAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (259, 39, 'TUCURRIQUE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (260, 39, 'PEJIBAYE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (261, 40, 'TURRIALBA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (262, 40, 'LA SUIZA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (263, 40, 'PERALTA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (264, 40, 'SANTA CRUZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (265, 40, 'SANTA TERESITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (266, 40, 'PAVONES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (267, 40, 'TUIS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (268, 40, 'TAYUTIC');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (269, 40, 'SANTA ROSA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (270, 40, 'TRES EQUIS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (271, 40, 'LA ISABEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (272, 40, 'CHIRRIPÓ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (273, 41, 'PACAYAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (274, 41, 'CERVANTES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (275, 41, 'CAPELLADES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (276, 42, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (277, 42, 'COT');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (278, 42, 'POTRERO CERRADO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (279, 42, 'CIPRESES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (280, 42, 'SANTA ROSA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (281, 43, 'EL TEJAR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (282, 43, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (283, 43, 'TOBOSI');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (284, 43, 'PATIO DE AGUA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (285, 44, 'HEREDIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (286, 44, 'MERCEDES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (287, 44, 'SAN FRANCISCO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (288, 44, 'ULLOA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (289, 44, 'VARABLANCA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (290, 45, 'BARVA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (291, 45, 'SAN PEDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (292, 45, 'SAN PABLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (293, 45, 'SAN ROQUE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (294, 45, 'SANTA LUCÍA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (295, 45, 'SAN JOSÉ DE LA MONTAÑA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (296, 46, 'SAN VICENTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (297, 46, 'SAN MIGUEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (298, 46, 'PARACITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (299, 46, 'SANTO TOMÁS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (300, 46, 'SANTA ROSA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (301, 46, 'TURES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (302, 46, 'PARÁ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (303, 47, 'SANTA BÁRBARA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (304, 47, 'SAN PEDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (305, 47, 'SAN JUAN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (306, 47, 'JESÚS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (307, 47, 'SANTO DOMINGO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (308, 47, 'PURABÁ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (309, 48, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (310, 48, 'SAN JOSECITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (311, 48, 'SANTIAGO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (312, 48, 'ÁNGELES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (313, 48, 'CONCEPCIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (314, 49, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (315, 49, 'SAN JOSÉ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (316, 49, 'CONCEPCIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (317, 49, 'SAN FRANCISCO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (318, 50, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (319, 50, 'LA RIBERA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (320, 50, 'LA ASUNCIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (321, 51, 'SAN JOAQUÍN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (322, 51, 'BARRANTES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (323, 51, 'LLORENTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (324, 52, 'SAN PABLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (325, 53, 'PUERTO VIEJO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (326, 53, 'LA VIRGEN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (327, 53, 'LAS HORQUETAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (328, 53, 'LLANURAS DEL GASPAR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (329, 53, 'CUREÑA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (330, 54, 'LIBERIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (331, 54, 'CAÑAS DULCES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (332, 54, 'MAYORGA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (333, 54, 'NACASCOLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (334, 54, 'CURUBANDÉ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (335, 55, 'NICOYA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (336, 55, 'MANSIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (337, 55, 'SAN ANTONIO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (338, 55, 'QUEBRADA HONDA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (339, 55, 'SÁMARA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (340, 55, 'NOSARA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (341, 55, 'BELÉN DE NOSARITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (342, 56, 'SANTA CRUZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (343, 56, 'BOLSÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (344, 56, 'VEINTISIETE DE ABRIL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (345, 56, 'TEMPATE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (346, 56, 'CARTAGENA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (347, 56, 'CUAJINIQUIL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (348, 56, 'DIRIÁ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (349, 56, 'CABO VELAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (350, 56, 'TAMARINDO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (351, 57, 'BAGACES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (352, 57, 'LA FORTUNA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (353, 57, 'MOGOTE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (354, 57, 'RÍO NARANJO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (355, 58, 'FILADELFIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (356, 58, 'PALMIRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (357, 58, 'SARDINAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (358, 58, 'BELÉN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (359, 59, 'CAÑAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (360, 59, 'PALMIRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (361, 59, 'SAN MIGUEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (362, 59, 'BEBEDERO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (363, 59, 'POROZAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (364, 60, 'LAS JUNTAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (365, 60, 'SIERRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (366, 60, 'SAN JUAN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (367, 60, 'COLORADO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (368, 61, 'TILARÁN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (369, 61, 'QUEBRADA GRANDE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (370, 61, 'TRONADORA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (371, 61, 'SANTA ROSA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (372, 61, 'LÍBANO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (373, 61, 'TIERRAS MORENAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (374, 61, 'ARENAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (375, 62, 'CARMONA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (376, 62, 'SANTA RITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (377, 62, 'ZAPOTAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (378, 62, 'SAN PABLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (379, 62, 'PORVENIR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (380, 62, 'BEJUCO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (381, 63, 'LA CRUZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (382, 63, 'SANTA CECILIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (383, 63, 'LA GARITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (384, 63, 'SANTA ELENA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (385, 64, 'HOJANCHA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (386, 64, 'MONTE ROMO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (387, 64, 'PUERTO CARRILLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (388, 64, 'HUACAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (389, 65, 'PUNTARENAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (390, 65, 'PITAHAYA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (391, 65, 'CHOMES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (392, 65, 'LEPANTO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (393, 65, 'PAQUERA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (394, 65, 'MANZANILLO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (395, 65, 'GUACIMAL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (396, 65, 'BARRANCA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (397, 65, 'MONTE VERDE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (398, 65, 'CÓBANO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (399, 65, 'CHACARITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (400, 65, 'CHIRA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (401, 65, 'ACAPULCO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (402, 65, 'EL ROBLE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (403, 65, 'ARANCIBIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (404, 66, 'ESPÍRITU SANTO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (405, 66, 'SAN JUAN GRANDE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (406, 66, 'MACACONA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (407, 66, 'SAN RAFAEL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (408, 66, 'SAN JERÓNIMO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (409, 66, 'CALDERA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (410, 67, 'BUENOS AIRES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (411, 67, 'VOLCÁN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (412, 67, 'POTRERO GRANDE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (413, 67, 'BORUCA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (414, 67, 'PILAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (415, 67, 'COLINAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (416, 67, 'CHÁNGUENA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (417, 67, 'BIOLLEY');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (418, 67, 'BRUNKA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (419, 68, 'MIRAMAR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (420, 68, 'LA UNIÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (421, 68, 'SAN ISIDRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (422, 69, 'PUERTO CORTÉS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (423, 69, 'PALMAR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (424, 69, 'SIERPE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (425, 69, 'BAHÍA BALLENA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (426, 69, 'PIEDRAS BLANCAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (427, 69, 'BAHÍA DRAKE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (428, 70, 'QUEPOS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (429, 70, 'SAVEGRE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (430, 70, 'NARANJITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (431, 71, 'GOLFITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (432, 71, 'PUERTO JIMÉNEZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (433, 71, 'GUAYCARÁ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (434, 71, 'PAVÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (435, 72, 'SAN VITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (436, 72, 'SABALITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (437, 72, 'AGUABUENA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (438, 72, 'LIMONCITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (439, 72, 'PITTIER');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (440, 72, 'GUTIERREZ BRAUN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (441, 73, 'PARRITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (442, 74, 'CORREDOR');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (443, 74, 'LA CUESTA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (444, 74, 'CANOAS');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (445, 74, 'LAUREL');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (446, 75, 'JACÓ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (447, 75, 'TÁRCOLES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (448, 76, 'LIMÓN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (449, 76, 'VALLE LA ESTRELLA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (450, 76, 'MATAMA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (451, 77, 'GUÁPILES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (452, 77, 'JIMÉNEZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (453, 77, 'RITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (454, 77, 'ROXANA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (455, 77, 'CARIARI');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (456, 77, 'COLORADO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (457, 77, 'LA COLONIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (458, 78, 'SIQUIRRES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (459, 78, 'PACUARITO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (460, 78, 'FLORIDA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (461, 78, 'GERMANIA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (462, 78, 'EL CAIRO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (463, 78, 'ALEGRÍA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (464, 79, 'BRATSI');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (465, 79, 'SIXAOLA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (466, 79, 'CAHUITA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (467, 79, 'TELIRE');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (468, 80, 'MATINA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (469, 80, 'BATÁN');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (470, 80, 'CARRANDI');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (471, 81, 'GUÁCIMO');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (472, 81, 'MERCEDES');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (473, 81, 'POCORA');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (474, 81, 'RÍO JIMÉNEZ');
INSERT INTO Distrito (distritoID, cantonID, nombre) VALUES (475, 81, 'DUACARÍ');




SET IDENTITY_INSERT Distrito OFF;
