DELETE FROM Pais;
DBCC CHECKIDENT (Pais, RESEED, 0);

SET IDENTITY_INSERT Pais ON;

INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (1, 'AFGANISTÁN', '93');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (2, 'ALBANIA', '355');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (3, 'ALEMANIA', '49');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (4, 'ALGERIA', '213');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (5, 'ANDORRA', '376');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (6, 'ANGOLA', '244');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (7, 'ANGUILA', '1264');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (8, 'ANTÁRTIDA', '672');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (9, 'ANTIGUA Y BARBUDA', '1268');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (10, 'ANTILLAS NEERLANDESAS', '599');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (11, 'ARABIA SAUDITA', '966');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (12, 'ARGENTINA', '54');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (13, 'ARMENIA', '374');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (14, 'ARUBA', '297');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (15, 'AUSTRALIA', '61');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (16, 'AUSTRIA', '43');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (17, 'AZERBAYÁN', '994');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (18, 'BÉLGICA', '32');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (19, 'BAHAMAS', '1242');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (20, 'BAHREIN', '973');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (21, 'BANGLADESH', '880');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (22, 'BARBADOS', '1246');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (23, 'BELICE', '501');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (24, 'BENÍN', '229');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (25, 'BHUTÁN', '975');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (26, 'BIELORRUSIA', '375');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (27, 'BIRMANIA', '95');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (28, 'BOLIVIA', '591');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (29, 'BOSNIA Y HERZEGOVINA', '387');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (30, 'BOTSUANA', '267');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (31, 'BRASIL', '55');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (32, 'BRUNÉI', '673');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (33, 'BULGARIA', '359');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (34, 'BURKINA FASO', '226');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (35, 'BURUNDI', '257');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (36, 'CABO VERDE', '238');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (37, 'CAMBOYA', '855');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (38, 'CAMERÚN', '237');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (39, 'CANADÁ', '1');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (40, 'CHAD', '235');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (41, 'CHILE', '56');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (42, 'CHINA', '86');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (43, 'CHIPRE', '357');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (44, 'CIUDAD DEL VATICANO', '39');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (45, 'COLOMBIA', '57');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (46, 'COMORAS', '269');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (47, 'CONGO', '242');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (48, 'CONGO', '243');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (49, 'COREA DEL NORTE', '850');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (50, 'COREA DEL SUR', '82');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (51, 'COSTA DE MARFIL', '225');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (52, 'COSTA RICA', '506');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (53, 'CROACIA', '385');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (54, 'CUBA', '53');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (55, 'DINAMARCA', '45');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (56, 'DOMINICA', '1767');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (57, 'ECUADOR', '593');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (58, 'EGIPTO', '20');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (59, 'EL SALVADOR', '503');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (60, 'EMIRATOS ÁRABES UNIDOS', '971');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (61, 'ERITREA', '291');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (62, 'ESLOVAQUIA', '421');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (63, 'ESLOVENIA', '386');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (64, 'ESPAÑA', '34');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (65, 'ESTADOS UNIDOS DE AMÉRICA', '1');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (66, 'ESTONIA', '372');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (67, 'ETIOPÍA', '251');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (68, 'FILIPINAS', '63');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (69, 'FINLANDIA', '358');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (70, 'FIYI', '679');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (71, 'FRANCIA', '33');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (72, 'GABÓN', '241');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (73, 'GAMBIA', '220');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (74, 'GEORGIA', '995');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (75, 'GHANA', '233');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (76, 'GIBRALTAR', '350');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (77, 'GRANADA', '1473');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (78, 'GRECIA', '30');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (79, 'GROENLANDIA', '299');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (80, 'GUADALUPE', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (81, 'GUAM', '1671');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (82, 'GUATEMALA', '502');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (83, 'GUAYANA FRANCESA', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (84, 'GUERNSEY', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (85, 'GUINEA', '224');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (86, 'GUINEA ECUATORIAL', '240');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (87, 'GUINEA-BISSAU', '245');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (88, 'GUYANA', '592');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (89, 'HAITÍ', '509');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (90, 'HONDURAS', '504');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (91, 'HONG KONG', '852');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (92, 'HUNGRÍA', '36');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (93, 'INDIA', '91');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (94, 'INDONESIA', '62');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (95, 'IRÁN', '98');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (96, 'IRAK', '964');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (97, 'IRLANDA', '353');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (98, 'ISLA BOUVET', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (99, 'ISLA DE MAN', '44');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (100, 'ISLA DE NAVIDAD', '61');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (101, 'ISLA NORFOLK', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (102, 'ISLANDIA', '354');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (103, 'ISLAS BERMUDAS', '1441');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (104, 'ISLAS CAIMÁN', '1345');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (105, 'ISLAS COCOS (KEELING)', '61');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (106, 'ISLAS COOK', '682');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (107, 'ISLAS DE ÅLAND', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (108, 'ISLAS FEROE', '298');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (109, 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (110, 'ISLAS HEARD Y MCDONALD', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (111, 'ISLAS MALDIVAS', '960');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (112, 'ISLAS MALVINAS', '500');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (113, 'ISLAS MARIANAS DEL NORTE', '1670');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (114, 'ISLAS MARSHALL', '692');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (115, 'ISLAS PITCAIRN', '870');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (116, 'ISLAS SALOMÓN', '677');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (117, 'ISLAS TURCAS Y CAICOS', '1649');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (118, 'ISLAS ULTRAMARINAS MENORES DE ESTADOS UNIDOS', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (119, 'ISLAS VÍRGENES BRITÁNICAS','1284');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (120, 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', '1340');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (121, 'ISRAEL', '972');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (122, 'ITALIA', '39');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (123, 'JAMAICA', '1876');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (124, 'JAPÓN', '81');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (125, 'JERSEY', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (126, 'JORDANIA', '962');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (127, 'KAZAJISTÁN', '7');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (128, 'KENIA', '254');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (129, 'KIRGIZSTÁN', '996');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (130, 'KIRIBATI', '686');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (131, 'KUWAIT', '965');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (132, 'LÍBANO', '961');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (133, 'LAOS', '856');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (134, 'LESOTO', '266');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (135, 'LETONIA', '371');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (136, 'LIBERIA', '231');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (137, 'LIBIA', '218');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (138, 'LIECHTENSTEIN', '423');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (139, 'LITUANIA', '370');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (140, 'LUXEMBURGO', '352');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (141, 'MÉXICO', '52');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (142, 'MÓNACO', '377');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (143, 'MACAO', '853');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (144, 'MACEDÔNIA', '389');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (145, 'MADAGASCAR', '261');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (146, 'MALASIA', '60');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (147, 'MALAWI', '265');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (148, 'MALI', '223');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (149, 'MALTA', '356');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (150, 'MARRUECOS', '212');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (151, 'MARTINICA', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (152, 'MAURICIO', '230');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (153, 'MAURITANIA', '222');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (154, 'MAYOTTE', '262');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (155, 'MICRONESIA', '691');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (156, 'MOLDAVIA', '373');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (157, 'MONGOLIA', '976');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (158, 'MONTENEGRO', '382');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (159, 'MONTSERRAT', '1664');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (160, 'MOZAMBIQUE', '258');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (161, 'NAMIBIA', '264');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (162, 'NAURU', '674');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (163, 'NEPAL', '977');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (164, 'NICARAGUA', '505');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (165, 'NIGER', '227');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (166, 'NIGERIA', '234');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (167, 'NIUE', '683');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (168, 'NORUEGA', '47');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (169, 'NUEVA CALEDONIA', '687');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (170, 'NUEVA ZELANDA', '64');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (171, 'OMÁN', '968');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (172, 'PAÍSES BAJOS', '31');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (173, 'PAKISTÁN', '92');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (174, 'PALAU', '680');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (175, 'PALESTINA', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (176, 'PANAMÁ', '507');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (177, 'PAPÚA NUEVA GUINEA', '675');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (178, 'PARAGUAY', '595');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (179, 'PERÚ', '51');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (180, 'POLINESIA FRANCESA', '689');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (181, 'POLONIA', '48');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (182, 'PORTUGAL', '351');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (183, 'PUERTO RICO', '1');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (184, 'QATAR', '974');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (185, 'REINO UNIDO', '44');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (186, 'REPÚBLICA CENTROAFRICANA', '236');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (187, 'REPÚBLICA CHECA', '420');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (188, 'REPÚBLICA DOMINICANA', '1809');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (189, 'REUNIÓN', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (190, 'RUANDA', '250');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (191, 'RUMANÍA', '40');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (192, 'RUSIA', '7');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (193, 'SAHARA OCCIDENTAL', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (194, 'SAMOA', '685');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (195, 'SAMOA AMERICANA', '1684');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (196, 'SAN BARTOLOMÉ', '590');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (197, 'SAN CRISTÓBAL Y NIEVES', '1869');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (198, 'SAN MARINO', '378');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (199, 'SAN MARTÍN (FRANCIA)', '1599');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (200, 'SAN PEDRO Y MIQUELÓN', '508');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (201, 'SAN VICENTE Y LAS GRANADINAS', '1784');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (202, 'SANTA ELENA', '290');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (203, 'SANTA LUCÍA', '1758');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (204, 'SANTO TOMÉ Y PRÍNCIPE', '239');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (205, 'SENEGAL', '221');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (206, 'SERBIA', '381');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (207, 'SEYCHELLES', '248');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (208, 'SIERRA LEONA', '232');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (209, 'SINGAPUR', '65');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (210, 'SIRIA', '963');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (211, 'SOMALIA', '252');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (212, 'SRI LANKA', '94');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (213, 'SUDÁFRICA', '27');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (214, 'SUDÁN', '249');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (215, 'SUECIA', '46');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (216, 'SUIZA', '41');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (217, 'SURINÁM', '597');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (218, 'SVALBARD Y JAN MAYEN', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (219, 'SWAZILANDIA', '268');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (220, 'TADJIKISTÁN', '992');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (221, 'TAILANDIA', '66');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (222, 'TAIWÁN', '886');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (223, 'TANZANIA', '255');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (224, 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (225, 'TERRITORIOS AUSTRALES Y ANTÁRTICAS FRANCESES', '0');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (226, 'TIMOR ORIENTAL', '670');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (227, 'TOGO', '228');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (228, 'TOKELAU', '690');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (229, 'TONGA', '676');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (230, 'TRINIDAD Y TOBAGO', '1868');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (231, 'TUNEZ', '216');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (232, 'TURKMENISTÁN', '993');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (233, 'TURQUÍA', '90');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (234, 'TUVALU', '688');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (235, 'UCRANIA', '380');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (236, 'UGANDA', '256');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (237, 'URUGUAY', '598');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (238, 'UZBEKISTÁN', '998');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (239, 'VANUATU', '678');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (240, 'VENEZUELA', '58');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (241, 'VIETNAM', '84');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (242, 'WALLIS Y FUTUNA', '681');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (243, 'YEMEN', '967');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (244, 'YIBUTI', '253');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (245, 'ZAMBIA', '260');
INSERT INTO Pais (paisID, nombre, codigoTelefonico) VALUES (246, 'ZIMBABUE', '263');

SET IDENTITY_INSERT Pais OFF;
